name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Poetry
        shell: bash
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Install Dependencies
        working-directory: ./example-app
        shell: bash
        run: poetry install --no-root

  static_tests:
    needs: setup
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        test_type: ['lint', 'formatter', 'security']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Poetry
        shell: bash
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Install Dependencies
        working-directory: ./example-app
        shell: bash
        run: poetry install --no-root
        
      - name: Run ${{ matrix.test_type }}
        working-directory: ./example-app
        shell: bash
        run: poetry run task ${{ matrix.test_type }}

  unit_tests:
    needs: setup
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Poetry
        shell: bash
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Install Dependencies
        working-directory: ./example-app
        shell: bash
        run: poetry install --no-root
        
      - name: Run Unit Tests
        working-directory: ./example-app
        shell: bash
        run: poetry run task test
